@startmindmap
'https://plantuml.com/mindmap-diagram

* Учёт персональных финансов
** Внешний API
*** Запрос курсов валют
**** сервис ЦБ РФ
**** XML
*** Ответственный
**** Алексей
** Внутренний API
*** Модель данных
**** Ответственный
***** Галина
*** Связь с БД
**** ADO.Net + Dapper
**** Ответственный
***** Дарья
*** API
** БД
*** SQLite
*** Ответственные
**** Евгений
**** Михаил
** GUI
*** WPF
**** MVVM
*** Ответственный
**** Назар
@endmindmap
